//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long Invoice_Number { get; set; }
        public long Orders_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
