//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long Items_ID { get; set; }
        public long Cart_ID { get; set; }
        public long Commodity_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
