//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public long Orders_ID { get; set; }
        public long User_ID { get; set; }
        public long Cart_ID { get; set; }
        public long Payment_ID { get; set; }
        public long Shipment_ID { get; set; }
        public long OrdersStatus_Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual Cart Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual OrdersStatu OrdersStatu { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Shipment Shipment { get; set; }
        public virtual User User { get; set; }
    }
}
