//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public long Preference_ID { get; set; }
        public long User_ID { get; set; }
        public long Theme_ID { get; set; }
    
        public virtual Theme Theme { get; set; }
        public virtual User User { get; set; }
    }
}
